/* Generated By:JavaCC: Do not edit this line. DtdParserImplConstants.java */
package org.eclipse.sapphire.modeling.xml.dtd.internal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DtdParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAME_START_CHAR = 1;
  /** RegularExpression Id. */
  int NAME_CHAR = 2;
  /** RegularExpression Id. */
  int FIXED = 3;
  /** RegularExpression Id. */
  int IMPLIED = 4;
  /** RegularExpression Id. */
  int PCDATA = 5;
  /** RegularExpression Id. */
  int REQUIRED = 6;
  /** RegularExpression Id. */
  int CDATA = 7;
  /** RegularExpression Id. */
  int ANY = 8;
  /** RegularExpression Id. */
  int EMPTY = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int IDREF = 11;
  /** RegularExpression Id. */
  int IDREFS = 12;
  /** RegularExpression Id. */
  int ENTITY = 13;
  /** RegularExpression Id. */
  int ENTITIES = 14;
  /** RegularExpression Id. */
  int NMTOKEN = 15;
  /** RegularExpression Id. */
  int NMTOKENS = 16;
  /** RegularExpression Id. */
  int NOTATION = 17;
  /** RegularExpression Id. */
  int NAME = 18;
  /** RegularExpression Id. */
  int ENTITY_REF = 19;
  /** RegularExpression Id. */
  int QUOTEDSTR = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NAME_START_CHAR>",
    "<NAME_CHAR>",
    "\"#FIXED\"",
    "\"#IMPLIED\"",
    "\"#PCDATA\"",
    "\"#REQUIRED\"",
    "\"CDATA\"",
    "\"ANY\"",
    "\"EMPTY\"",
    "\"ID\"",
    "\"IDREF\"",
    "\"IDREFS\"",
    "\"ENTITY\"",
    "\"ENTITIES\"",
    "\"NMTOKEN\"",
    "\"NMTOKENS\"",
    "\"NOTATION\"",
    "<NAME>",
    "<ENTITY_REF>",
    "<QUOTEDSTR>",
    "<token of kind 21>",
    "<token of kind 22>",
    "<token of kind 23>",
    "\"<!ELEMENT\"",
    "\">\"",
    "\"(\"",
    "\"|\"",
    "\",\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"<!ATTLIST\"",
    "\"<!ENTITY\"",
    "\"%\"",
  };

}
