/* Generated By:JavaCC: Do not edit this line. DocumentationContentParserConstants.java */
package org.eclipse.sapphire.modeling.docsys.internal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DocumentationContentParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BR = 1;
  /** RegularExpression Id. */
  int PBR = 2;
  /** RegularExpression Id. */
  int LI_OPEN = 3;
  /** RegularExpression Id. */
  int LI_CLOSE = 4;
  /** RegularExpression Id. */
  int UL_OPEN = 5;
  /** RegularExpression Id. */
  int UL_CLOSE = 6;
  /** RegularExpression Id. */
  int OL_OPEN = 7;
  /** RegularExpression Id. */
  int OL_CLOSE = 8;
  /** RegularExpression Id. */
  int BOLD_OPEN = 9;
  /** RegularExpression Id. */
  int BOLD_CLOSE = 10;
  /** RegularExpression Id. */
  int CHARACTER = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[br/]\"",
    "\"[pbr/]\"",
    "\"[li]\"",
    "\"[/li]\"",
    "\"[ul]\"",
    "\"[/ul]\"",
    "\"[ol]\"",
    "\"[/ol]\"",
    "\"[b]\"",
    "\"[/b]\"",
    "<CHARACTER>",
  };

}
