/* Generated By:JavaCC: Do not edit this line. ScriptParserConstants.java */
package org.eclipse.sapphire.modeling.scripting.internal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR_OR_LITERAL = 2;
  /** RegularExpression Id. */
  int EQUALS = 3;
  /** RegularExpression Id. */
  int AND = 4;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int OPEN_PAR = 6;
  /** RegularExpression Id. */
  int CLOSE_PAR = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<VAR_OR_LITERAL>",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"(\"",
    "\")\"",
  };

}
